/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerVendas;
import javax.swing.JOptionPane;
import model.ModelCliente;
import model.ModelVendas;
import util.Formatador;

/**
 *
 * @author afbo2
 */
public class PagarVP extends javax.swing.JDialog {

    int codigoVenda;

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();

    ControllerVendas controllerVendas = new ControllerVendas();
    ModelVendas modelVendas = new ModelVendas();

    Formatador f = new Formatador();

    /**
     * Creates new form PagarVP
     */
    public PagarVP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelValorRecebido = new javax.swing.JPanel();
        jtfValorRecebido = new javax.swing.JFormattedTextField();
        jbPagarParte = new javax.swing.JButton();
        jbQuitarDivida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfValorPago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfValorPendente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtfValorRecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jtfValorRecebido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfValorRecebido.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout painelValorRecebidoLayout = new javax.swing.GroupLayout(painelValorRecebido);
        painelValorRecebido.setLayout(painelValorRecebidoLayout);
        painelValorRecebidoLayout.setHorizontalGroup(
            painelValorRecebidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelValorRecebidoLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jtfValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        painelValorRecebidoLayout.setVerticalGroup(
            painelValorRecebidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelValorRecebidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfValorRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );

        jbPagarParte.setBackground(new java.awt.Color(204, 255, 204));
        jbPagarParte.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbPagarParte.setText("Pagar uma parte");
        jbPagarParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPagarParteActionPerformed(evt);
            }
        });

        jbQuitarDivida.setBackground(new java.awt.Color(204, 255, 204));
        jbQuitarDivida.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbQuitarDivida.setText("Quitar Divida");
        jbQuitarDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitarDividaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informe o valor pago / quite essa divida");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Valor Pago");

        jtfValorPago.setEditable(false);
        jtfValorPago.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtfValorPago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfValorPago.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor Pendente");

        jtfValorPendente.setEditable(false);
        jtfValorPendente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtfValorPendente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfValorPendente.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jbPagarParte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbQuitarDivida)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(painelValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(230, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfValorPendente, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jtfValorPago))))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfValorPendente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPagarParte)
                    .addComponent(jbQuitarDivida))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbQuitarDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitarDividaActionPerformed
        modelVendas = controllerVendas.getVendasController(codigoVenda);
        int codigoCliente = modelVendas.getCliente();
        modelCliente = controllerCliente.getClienteController(codigoCliente);
        int respostaConfirmacao = JOptionPane.showConfirmDialog(
                rootPane,
                "Confirma ter recebido o valor de R$" + modelVendas.getVenValorLiquido() + "\n\n"
                + "Da venda efetuada para o cliente " + modelCliente.getCliNome(),
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );
        if (respostaConfirmacao == JOptionPane.NO_OPTION || respostaConfirmacao == JOptionPane.CLOSED_OPTION) {
            //sai do método
            return;
        }
        modelVendas.setVenEstado("pago");
        modelVendas.setVenValorPendente(0);
        modelVendas.setVenValorPago(modelVendas.getVenValorLiquido());
        if (controllerVendas.atualizarEstadoVendasController(modelVendas)) {
            JOptionPane.showMessageDialog(this, "Pagamento da divida efetuado com sucesso!!", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao efetuar o pagamento!!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbQuitarDividaActionPerformed

    private void jbPagarParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPagarParteActionPerformed
        if (jtfValorRecebido.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "favor preencha o valor que fracionado que foi recebido");
        } else {
            int codigoCliente = modelVendas.getCliente();
            double valorRecebido = (f.converterVirgulaParaPonto((jtfValorRecebido.getText())));
            modelVendas = controllerVendas.getVendasController(codigoVenda);
            modelCliente = controllerCliente.getClienteController(codigoCliente);
            modelVendas.setVenValorPago(valorRecebido);
            modelVendas.setVenValorPendente(modelVendas.getVenValorPendente() - valorRecebido);
            if (controllerVendas.atualizarValorVendasController(modelVendas)) {
                JOptionPane.showMessageDialog(this, "Pagamento de parte da divida realizado com sucesso!", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao efetuar o pagamento!!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jbPagarParteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagarVP dialog = new PagarVP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void receber(int pCodigo) {
        codigoVenda = pCodigo;
        modelVendas = controllerVendas.getVendasController(codigoVenda);
        carregarInfo();
    }

    private void carregarInfo() {
        jtfValorPago.setText(String.valueOf(modelVendas.getVenValorPago()));
        jtfValorPendente.setText(String.valueOf(modelVendas.getVenValorPendente()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbPagarParte;
    private javax.swing.JButton jbQuitarDivida;
    private javax.swing.JTextField jtfValorPago;
    private javax.swing.JTextField jtfValorPendente;
    private javax.swing.JFormattedTextField jtfValorRecebido;
    private javax.swing.JPanel painelValorRecebido;
    // End of variables declaration//GEN-END:variables
}
