/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import util.AtualizadorHorario;

/**
 *
 * @author afbo2
 */
public class ViewPrincipal extends javax.swing.JFrame {

    Relatorios relatorios;
    Caixa caixa;
    Estoque estoque;
    Clientes clientes;

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        dataHora();
        AtualizadorHorario.start(jtfHora);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        dataHora = new javax.swing.JPanel();
        jtfData = new javax.swing.JTextField();
        jtfHora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        icones = new javax.swing.JPanel();
        jbClientes = new javax.swing.JButton();
        jbEstoque = new javax.swing.JButton();
        jbRelatorios = new javax.swing.JButton();
        jbCaixa = new javax.swing.JButton();
        jbAjuda = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        textos = new javax.swing.JPanel();
        jlClientes = new javax.swing.JLabel();
        jlEstoque = new javax.swing.JLabel();
        jlRelatorios = new javax.swing.JLabel();
        jlCaixa = new javax.swing.JLabel();
        jlAjuda = new javax.swing.JLabel();
        jlSair = new javax.swing.JLabel();
        painelDesktop = new javax.swing.JLayeredPane();
        uJPanelImagem1 = new componentes.UJPanelImagem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vania'S System");
        setBackground(new java.awt.Color(255, 204, 255));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Vania's bg/loja-de-aplicativos.png")).getImage());
        setResizable(false);

        painelSuperior.setBackground(new java.awt.Color(51, 51, 51));
        painelSuperior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 120, 5));

        dataHora.setBackground(new java.awt.Color(51, 51, 51));
        dataHora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dataHora.setMaximumSize(new java.awt.Dimension(200, 70));
        dataHora.setMinimumSize(new java.awt.Dimension(200, 70));
        dataHora.setPreferredSize(new java.awt.Dimension(200, 70));
        dataHora.setLayout(new java.awt.GridLayout(2, 2, 0, 5));

        jtfData.setEditable(false);
        jtfData.setBackground(new java.awt.Color(51, 51, 51));
        jtfData.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jtfData.setForeground(new java.awt.Color(204, 204, 204));
        jtfData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfData.setText("DATA DO SISTEMA ");
        jtfData.setBorder(null);
        dataHora.add(jtfData);

        jtfHora.setEditable(false);
        jtfHora.setBackground(new java.awt.Color(51, 51, 51));
        jtfHora.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jtfHora.setForeground(new java.awt.Color(204, 204, 204));
        jtfHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfHora.setText("HORA DO SISTEMA");
        jtfHora.setBorder(null);
        jtfHora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtfHora.setFocusCycleRoot(true);
        dataHora.add(jtfHora);

        painelSuperior.add(dataHora);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vania's bg/icone_1.png"))); // NOI18N
        painelSuperior.add(jLabel1);

        menu.setBackground(new java.awt.Color(51, 51, 51));

        icones.setOpaque(false);
        icones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        jbClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vania's bg/pessoa-vip (1).png"))); // NOI18N
        jbClientes.setMaximumSize(new java.awt.Dimension(70, 70));
        jbClientes.setMinimumSize(new java.awt.Dimension(70, 70));
        jbClientes.setPreferredSize(new java.awt.Dimension(70, 70));
        jbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbClientesMouseExited(evt);
            }
        });
        jbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClientesActionPerformed(evt);
            }
        });
        icones.add(jbClientes);

        jbEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vania's bg/estoque (1)_1.png"))); // NOI18N
        jbEstoque.setMaximumSize(new java.awt.Dimension(70, 70));
        jbEstoque.setMinimumSize(new java.awt.Dimension(70, 70));
        jbEstoque.setPreferredSize(new java.awt.Dimension(70, 70));
        jbEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbEstoqueMouseExited(evt);
            }
        });
        jbEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstoqueActionPerformed(evt);
            }
        });
        icones.add(jbEstoque);

        jbRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vania's bg/market-analysis.png"))); // NOI18N
        jbRelatorios.setMaximumSize(new java.awt.Dimension(70, 70));
        jbRelatorios.setMinimumSize(new java.awt.Dimension(70, 70));
        jbRelatorios.setPreferredSize(new java.awt.Dimension(70, 70));
        jbRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbRelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbRelatoriosMouseExited(evt);
            }
        });
        jbRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatoriosActionPerformed(evt);
            }
        });
        icones.add(jbRelatorios);

        jbCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vania's bg/cesta-de-compras.png"))); // NOI18N
        jbCaixa.setMaximumSize(new java.awt.Dimension(70, 70));
        jbCaixa.setMinimumSize(new java.awt.Dimension(70, 70));
        jbCaixa.setPreferredSize(new java.awt.Dimension(70, 70));
        jbCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCaixaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCaixaMouseExited(evt);
            }
        });
        jbCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCaixaActionPerformed(evt);
            }
        });
        icones.add(jbCaixa);

        jbAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vania's bg/conta-bancaria.png"))); // NOI18N
        jbAjuda.setMaximumSize(new java.awt.Dimension(70, 70));
        jbAjuda.setMinimumSize(new java.awt.Dimension(70, 70));
        jbAjuda.setPreferredSize(new java.awt.Dimension(70, 70));
        icones.add(jbAjuda);

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vania's bg/exit.png"))); // NOI18N
        jbSair.setMaximumSize(new java.awt.Dimension(70, 70));
        jbSair.setMinimumSize(new java.awt.Dimension(70, 70));
        jbSair.setPreferredSize(new java.awt.Dimension(70, 70));
        icones.add(jbSair);

        textos.setBackground(new java.awt.Color(51, 51, 51));

        jlClientes.setBackground(new java.awt.Color(0, 0, 0));
        jlClientes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlClientes.setForeground(new java.awt.Color(255, 255, 255));
        jlClientes.setText("Clientes");

        jlEstoque.setBackground(new java.awt.Color(0, 0, 0));
        jlEstoque.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jlEstoque.setText("Estoque");

        jlRelatorios.setBackground(new java.awt.Color(0, 0, 0));
        jlRelatorios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        jlRelatorios.setText("Relatorios");

        jlCaixa.setBackground(new java.awt.Color(0, 0, 0));
        jlCaixa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlCaixa.setForeground(new java.awt.Color(255, 255, 255));
        jlCaixa.setText("Caixa");

        jlAjuda.setBackground(new java.awt.Color(0, 0, 0));
        jlAjuda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlAjuda.setForeground(new java.awt.Color(255, 255, 255));
        jlAjuda.setText("Boletos");

        jlSair.setBackground(new java.awt.Color(0, 0, 0));
        jlSair.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlSair.setForeground(new java.awt.Color(255, 255, 255));
        jlSair.setText("Sair");

        javax.swing.GroupLayout textosLayout = new javax.swing.GroupLayout(textos);
        textos.setLayout(textosLayout);
        textosLayout.setHorizontalGroup(
            textosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlClientes)
                .addGap(47, 47, 47)
                .addComponent(jlEstoque)
                .addGap(45, 45, 45)
                .addComponent(jlRelatorios)
                .addGap(47, 47, 47)
                .addComponent(jlCaixa)
                .addGap(62, 62, 62)
                .addComponent(jlAjuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jlSair)
                .addGap(31, 31, 31))
        );
        textosLayout.setVerticalGroup(
            textosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(textosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlClientes)
                    .addComponent(jlEstoque)
                    .addComponent(jlRelatorios)
                    .addComponent(jlCaixa)
                    .addComponent(jlAjuda)
                    .addComponent(jlSair)))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(textos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(icones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(icones, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        painelSuperior.add(menu);

        painelDesktop.setBackground(new java.awt.Color(255, 204, 255));
        painelDesktop.setOpaque(true);

        uJPanelImagem1.setBackground(new java.awt.Color(255, 204, 204));
        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\afbo2\\Desktop\\Vania's bg\\bg.jpg"));
        uJPanelImagem1.setMaximumSize(new java.awt.Dimension(1000, 500));

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1622, Short.MAX_VALUE)
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        painelDesktop.setLayer(uJPanelImagem1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(painelDesktop))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelDesktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClientesActionPerformed
        if (clientes == null) {
            clientes = new Clientes();
            this.painelDesktop.add(clientes);
            setPosicao(clientes);
        }
        clientes.Refresh();
        clientes.setVisible(true);
        clientes.moveToFront();
    }//GEN-LAST:event_jbClientesActionPerformed

    private void jbEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstoqueActionPerformed
        if (estoque == null) {
            estoque = new Estoque();
            this.painelDesktop.add(estoque);
            setPosicao(estoque);

        }
        estoque.Refresh();
        estoque.setVisible(true);
        estoque.moveToFront();
    }//GEN-LAST:event_jbEstoqueActionPerformed

    private void jbRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatoriosActionPerformed
        if (relatorios == null) {
            relatorios = new Relatorios();
            this.painelDesktop.add(relatorios);
            setPosicao(relatorios);

        }
        relatorios.Refresh();
        relatorios.setVisible(true);
        relatorios.moveToFront();
    }//GEN-LAST:event_jbRelatoriosActionPerformed

    private void jbCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCaixaActionPerformed
        if (caixa == null) {
            caixa = new Caixa();
            this.painelDesktop.add(caixa);
            setPosicao(caixa);

        }
        caixa.Refresh();
        caixa.setVisible(true);
        caixa.moveToFront();
    }//GEN-LAST:event_jbCaixaActionPerformed

    private void jbClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbClientesMouseEntered
        jbClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255),
                new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));
        jbClientes.setBackground(new java.awt.Color(255, 153, 204));
        jlClientes.setForeground(new java.awt.Color(255, 153, 204));
    }//GEN-LAST:event_jbClientesMouseEntered

    private void jbClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbClientesMouseExited
        jbClientes.setBorder(null);
        jbClientes.setBackground(null);
        jlClientes.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbClientesMouseExited

    private void jbEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEstoqueMouseEntered
        jbEstoque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255),
                new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));
        jbEstoque.setBackground(new java.awt.Color(255, 153, 204));
        jbEstoque.setForeground(new java.awt.Color(255, 153, 204));
    }//GEN-LAST:event_jbEstoqueMouseEntered

    private void jbEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEstoqueMouseExited
        jbEstoque.setBorder(null);
        jbEstoque.setBackground(null);
        jbEstoque.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbEstoqueMouseExited

    private void jbRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRelatoriosMouseEntered
        jbRelatorios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255),
                new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));
        jbRelatorios.setBackground(new java.awt.Color(255, 153, 204));
        jbRelatorios.setForeground(new java.awt.Color(255, 153, 204));
    }//GEN-LAST:event_jbRelatoriosMouseEntered

    private void jbRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRelatoriosMouseExited
        jbRelatorios.setBorder(null);
        jbRelatorios.setBackground(null);
        jbRelatorios.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbRelatoriosMouseExited

    private void jbCaixaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCaixaMouseEntered
        jbCaixa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 255),
                new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(255, 204, 255)));
        jbCaixa.setBackground(new java.awt.Color(255, 153, 204));
        jbCaixa.setForeground(new java.awt.Color(255, 153, 204));
    }//GEN-LAST:event_jbCaixaMouseEntered

    private void jbCaixaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCaixaMouseExited
        jbCaixa.setBorder(null);
        jbCaixa.setBackground(null);
        jbCaixa.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbCaixaMouseExited

    private void dataHora() {
        LocalDateTime agora = LocalDateTime.now();
        DateTimeFormatter formatterData = DateTimeFormatter.ofPattern("dd/MM/uuuu");
        String dataFormatada = formatterData.format(agora);

        DateTimeFormatter formatterHora = DateTimeFormatter.ofPattern("HH:mm:ss");
        String horaFormatada = formatterHora.format(agora);

        jtfHora.setText(horaFormatada);
        jtfData.setText(dataFormatada);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataHora;
    private javax.swing.JPanel icones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAjuda;
    private javax.swing.JButton jbCaixa;
    private javax.swing.JButton jbClientes;
    private javax.swing.JButton jbEstoque;
    private javax.swing.JButton jbRelatorios;
    private javax.swing.JButton jbSair;
    private javax.swing.JLabel jlAjuda;
    private javax.swing.JLabel jlCaixa;
    private javax.swing.JLabel jlClientes;
    private javax.swing.JLabel jlEstoque;
    private javax.swing.JLabel jlRelatorios;
    private javax.swing.JLabel jlSair;
    private javax.swing.JTextField jtfData;
    private javax.swing.JTextField jtfHora;
    private javax.swing.JPanel menu;
    private javax.swing.JLayeredPane painelDesktop;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JPanel textos;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables

    //centralizar o JInternnalFrame de acordo com o 
    public void setPosicao(JInternalFrame frame) {
        Dimension desktopSize = painelDesktop.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

}
